# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dapper < Formula
  desc "Docker build wrapper (Dapper)"
  homepage "https://github.com/seanly/dapper"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/seanly/dapper/releases/download/v1.0.0/dapper_1.0.0_darwin_amd64.tar.gz"
      sha256 "a83b2a4c1e95f51b1cf5b9a3e9fbcd203fcddcdea9d8ed59cc96ef8eccdf24fa"

      def install
        bin.install "dapper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/seanly/dapper/releases/download/v1.0.0/dapper_1.0.0_darwin_arm64.tar.gz"
      sha256 "7f2c2e4f900e9e9dfdd93667952015d5d6408090973f5e69d8eaee9cb8ffdc22"

      def install
        bin.install "dapper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/seanly/dapper/releases/download/v1.0.0/dapper_1.0.0_linux_amd64.tar.gz"
      sha256 "d814539f455cd4e3038a596518bd12f31e5d7a5610c1f621a5783b5b4decb774"
      def install
        bin.install "dapper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/seanly/dapper/releases/download/v1.0.0/dapper_1.0.0_linux_arm64.tar.gz"
      sha256 "628a087bb8b639261c5efffab52f0dbcbc1c9daed8c8e8b8311a2e199a991432"
      def install
        bin.install "dapper"
      end
    end
  end

  test do
    system "#{bin}/dapper", "--version"
  end
end
